### PR TITLE
Allow multiple connections

### PR DESCRIPTION
**Pull request by apeace**
Don't know if you'll like this, but this is how I would prefer to use bolt in my apps. There is no connect() or name() method--a config object is passed in to instantiate a "mesh" object. The mesh object only has on() and emit() methods.

This would mean that, in the same JS file, you could connect to multiple different servers, or the same server under multiple names. With the current module, this is impossible.

Also gets rid of the `(function(){` wrapper, which doesn't add security in node modules.

I tested this quickly, but not very much. I guess tests are the next thing that bolt needs :P

### CODE REVIEW

**Comment by ecto** [comment]
Could you roll back and provide a separate commit for debug mode? That would be really useful

Why delimiter.toUpperCase()?

**Comment by ecto** [comment]
Can you explain why immediate execution doesn't provide privacy?

**Comment by apeace** [comment]
Well, these two are equivalent:

``` javascript
var secret_obj = { a: 2, b: 4 }; // can't be accessed from outside module
module.exports = { b: secret_obj.b } // export just the one property
```

``` javascript
(function(){
var secret_obj = { a: 2, b: 4 }; // can't be accessed from outside module
module.exports = { b: secret_obj.b } // export just the one property
})()
```

Also, the upper-cased DELIMITER is just a style thing, denoting a "constant" :P

**Comment by apeace** [comment]
I moved all this to somewhere else...

**Pull request closed without merging**
